### PR TITLE
lets get design decision tokens in documentation

### PR DESCRIPTION
**Pull request by sturobson**
I have:

updated to `vf-design-tokens` to generate a .json file and put the button tokens in a `.tokens.scss` file.
created a helper.js to try and get the `if` statement to generate to the tokens in the `vf-button` readme file

### CODE REVIEW

**Comment by khawkins98** [comment]
I think the helper.js is missing from this branch? Presumably that's the `helpers.getTokenFile`?

Also, it looks like you're tying to access a data object at `components.button.properties`, but I don't think `components` is defined in this template's scope.

May just be that some of the technical plumbing is missing from this commit?

**Comment by sturobson** [comment]
the `components.` bit is needed because I've nested the JS (which I'll upload) into `_data/components/buttons.js' so it's needed. Like we do with the tokens

**Comment by sturobson** [comment]
What I want is using:
```
const path = require('path');

module.exports = {
  getTokenFile(text) {

    return "components." + path.basename(__filename) + ".properties";
  }
};
```

but the `path.basename(__filename)` to be the component's `title` in the `README.md`. Doing this with nunjucks alone doesn't seem to work although I can get it to print out the correct thing.

**Comment by khawkins98** [comment]
The property name wasn't being interpreted as a variable, this fixes it https://github.com/visual-framework/vf-core/pull/1365/commits/2c62006a5bb694d7700049ea7d7618a7e312853d

I'll probably have a couple other comments on the build logic, but need to spend more time looking at "the big picture"

**Comment by sturobson** [comment]
> need to spend more time looking at "the big picture"

I should write the thoughts going on in my head - which might help

**Comment by sturobson** [comment]
As much as I think this will be a good thing moving forward and helpful to assist teams that want to use the VF but bring their own styles this should be closed here and no further development work made on it in lieu of time I have left on the project.

**Pull request closed without merging**
