### PR TITLE
deprecates and removes old components

### PR DESCRIPTION
**Pull request by sturobson**
moving to the Beta release we have a few components that are no longer in use and should no longer _be_ used.

This PR sets to remove:

- [x] vf-contact (replaced by vf-summary--profile)
- [x] vf-job-description (replaced by vf-summary--job)
- [x] vf-news-item (replaced by vf-summary--news)
- [x] vf-snippet (replaced by vf-summary--article)
- [x] vf-data-protection-banner (replaced by vf-banner)
- [x] vf-factoid (replaced by vf-box--factoid)
- [x] vf-tags (replaces by vf-badge)

things to do per component:

- each component has its Sass wrapped in `.vf-body:not(.vf-disable-deprecated) { … }`.
- each component has `<h2>This component has been <span style="color: rgb(228, 0, 70);">deprecated</span>. Please use the <a class="vf-link" href="#"new</a> component.</h2>` in the README.md file.
- each component has `status: deprecated` in the config file.
- each component has `component-type: deprecated` in the `context` of the config file.

things to do for NPM:

- `npm deprecate @visual-framework/component "no longer supported use the @visual-framework/component instead"`

things to do in the repo:

- delete the component and push to this PR

(some of the above needs adding to the deprecation documentation)

### CODE REVIEW

**Comment by sturobson** [comment]
There are 3 updates required in the content hub repository for this to work:

[update to factoid](https://gitlab.ebi.ac.uk/emblorg/content-hub/merge_requests/125)
[update to contact[(https://gitlab.ebi.ac.uk/emblorg/content-hub/merge_requests/124)

We also need a component that fits where `vf-news-item--snippet` was as this is a component used. 

I'll open a separate task for this - maybe we do have `vf-snippet` and then have `vf-snippet--news` etc.

**Comment by khawkins98** [comment]
As the ContentHub/dev.beta.embl.org sites will be using the `alpha.4` snapshot (https://dev.assets.emblstatic.net/vf/alpha.4/css/styles.css), we can proceed here with these changes to vf-core without blowing things up.

**Comment by sturobson** [comment]
new issue regarding the vf-snippet pattern and variants -- #345

**Comment by sturobson** [comment]
> As the ContentHub/dev.beta.embl.org sites will be using the `alpha.4` snapshot (https://dev.assets.emblstatic.net/vf/v2.0.0-alpha.4/css/styles.css), we can proceed here with these changes to vf-core without blowing things up.

You can probably hold off on those merge requests for the Content Hub (CHub) too?

**Comment by sturobson** [comment]
As Alpha 4 is snap-shotted (snapshat?) I think this is ready for review, and merge.

**Comment by khawkins98** [comment]
Partly addresses #336.

**Pull request merged**
