### PR TITLE
Refactor: vf-frctl-theme

### PR DESCRIPTION
**Pull request by khawkins98**
With the recent changes in the fractal theming layer (see: #1260) our old vf-frctl-theme is no longer sustainable and needs a complete refactor.

The best way to do this is to clone the revised frctl-mandlebrot theme and merge in our old code.

This presents and opportunity to reassess vf-frctl-theme to be more vf-core development focused. Especially as the theme is no longer deployed to the web.

High-level ideas:

- something closer to the default mandlebrot theme (future sustainability)
- preserve some of the mandlebrot features (searching, resizing)
- apply VF things where it matters (fonts, colours, key principles)

This commit starts that work.

### CODE REVIEW

**Comment by sturobson** [comment]
As we are using Eleventy for the user-facing site - I wonder if it would be easier to resort to the generic fractal theme for development now? 

It can still be 'themed' lightly with corporate typography and colours. 

The bonus would mean we'd have to worry about this less as it's more of a 'development environment' making https://stable.visual-framework.dev the thing to work on and improve.

That's my two cents

**Comment by sturobson** [comment]
simply removing the custom theme from `fractal.js` has it working 'as expected'. 

It'd be interesting to see if performance improves -- it might be Big Sur (probably is) but developing in `vf-core` has been a slow slog recently (since upgrading, at least).

**Comment by sturobson** [comment]
a quick update -- using the default theme - it's still slow as a slow thing 

slow slow slow

**Comment by khawkins98** [comment]
Yeah, i'm not sure there is still a use case to have our own customised theme for fractal. 

I'd be happy to rever to mandlebrot and we can make a custom theme if/when needed. 

---

As for performance, it's still been pretty fast for me. I'm on node `v12.16.1` and still using Catalina. 

## Timings

17 seconds from `gulp vf-dev` to get the whole thing up and running in the browser.

Trimmed log: 

```
[09:49:28] Using gulpfile ~/Documents/GitHub/vf-core/tools/vf-core/gulpfile.js
[09:49:28] Starting 'vf-dev'...
[09:49:28] Starting 'vf-clean'...
[09:49:28] Finished 'vf-clean' after 142 ms
[09:49:28] Starting 'vf-css'...
[09:49:28] Starting 'vf-css:package-info'...
[09:49:29] Finished 'vf-css:package-info' after 639 ms
[09:49:29] Starting 'vf-css:build'...
[09:49:31] Finished 'vf-css:build' after 2 s
[09:49:31] Finished 'vf-css' after 2.64 s
[09:49:31] Starting 'vf-scripts'...
[09:49:31] Starting 'vf-scripts:es5'...
[09:49:33] Finished 'vf-scripts:es5' after 1.7 s
[09:49:33] Starting 'vf-scripts:modern'...
[09:49:33] Finished 'vf-scripts:modern' after 3.91 ms
[09:49:33] Starting 'vf-lint:js-soft-fail'...
[09:49:34] Finished 'vf-lint:js-soft-fail' after 1.03 s
[09:49:34] Finished 'vf-scripts' after 2.74 s
[09:49:34] Starting 'vf-component-assets'...
[09:49:34] Starting 'vf-component-assets:directory'...
[09:49:34] Starting 'vf-component-assets:compiled-css'...
[09:49:34] Starting 'vf-component-assets:js'...
[09:49:35] Finished 'vf-component-assets:compiled-css' after 667 ms
[09:49:35] Finished 'vf-component-assets:js' after 845 ms
[09:49:35] Finished 'vf-component-assets:directory' after 898 ms
[09:49:35] Finished 'vf-component-assets' after 898 ms
[09:49:35] Starting 'vf-fractal:start'...
✔ Your Visual Framework component library is available at http://localhost:3000
[09:49:37] Finished 'vf-fractal:start' after 2.67 s
[09:49:37] Starting 'vf-lint:scss-soft-fail'...
[09:49:44] Finished 'vf-lint:scss-soft-fail' after 6.23 s
[09:49:44] Starting 'vf-lint:js-soft-fail'...
[09:49:45] Finished 'vf-lint:js-soft-fail' after 995 ms
[09:49:45] Starting 'vf-templates-precompile'...
[09:49:45] Finished 'vf-templates-precompile' after 273 ms
[09:49:45] Starting 'vf-watch'...
```

And then when editing a njk file (browser refresh happens within about 1 second):

```
[09:52:26] Starting 'vf-templates-precompile'...
[09:52:26] Finished 'vf-templates-precompile' after 305 ms
```

For CSS edits:

```
[09:53:53] Starting 'vf-css'...
[09:53:53] Starting 'vf-css:package-info'...
[09:53:54] Finished 'vf-css:package-info' after 1.22 s
[09:53:54] Starting 'vf-css:build'...
[09:53:55] Finished 'vf-css:build' after 1.24 s
[09:53:55] Finished 'vf-css' after 2.46 s
```

**Comment by khawkins98** [comment]
Made a quick PR #1262 that would swap to the mandlebrot theme. 

We could go with it or not :)

**Comment by khawkins98** [comment]
With #1262 this is no longer needed

**Pull request closed without merging**
