### PR TITLE
Added button link theme variant

### PR DESCRIPTION
**Pull request by nitinja**
Reference: https://docs.google.com/document/d/1pA436W5M0ZPhlplfIXhTzo9vThvKhE4kkdGMzUT9nHs/edit?ts=60a6779a

### CODE REVIEW

**Review by sturobson — APPROVED** [review]

**Comment by sturobson** [comment]
I kinda feel this came about out of confusion rather than necessity. 

As now we've created more CSS to make something more understandable -- where I would have expected the HTML element being an `<a>` and not a `<button>` would be sufficient.

Let's merge it in anyhow.

**Comment by nitinja** [comment]
@sturobson not sure I fully agree.
I have been developing lots of enterprise apps: need for a "button that looks like a link" is very much real and we just cant use regular links as buttons for accessibility reason. [Here is detailed explanation](https://accessibility.oit.ncsu.edu/it-accessibility-at-nc-state/developers/accessibility-handbook/mouse-and-keyboard-events/links/link-behavior/).

**Comment by sturobson** [comment]
I perhaps didn't make it clear. 

There already was a 'button as a link' option here … you would replace the `<button>` with an `<a href="">`.

What we've done here is added extra code to make up for confusion of a 'button link' in the documentation because of how it was worded, and the documentation that has gone with it.

**Comment by nitinja** [comment]
@sturobson I beg to differ

`href=""` is an [invalid URL value](https://html.spec.whatwg.org/multipage/links.html#attr-hyperlink-href)  
`href="#"` takes users to top of the page, unless you `event.preventDefault()` so it's not usable as a button.
omitting href value or href attribute itself makes the link un-focusable by keyboard, so not accessible.

This component is very much required.

**Comment by sturobson** [comment]
I'm clearly not explaining this well.

**Pull request merged**
