### PR TITLE
enhancement: component library navigation

### PR DESCRIPTION
**Pull request by khawkins98**
This continues the ongoing work to improve the component library as discussed in #1175:

- begins to vf-tree ify the navigation
- processes the README.md to present a more readable overview
- moves verbose code readouts and install text to vf-details
- puts code examples in "boxes"
- general tidy

More to be done but I think it's a good stride in the right direction.

Will be follow on work to tidy up the READMEs

Could merge this one now and revisit later or keep stashed and work here.

### CODE REVIEW

**Comment by khawkins98** [comment]
Screenshots 

image

image

**Comment by khawkins98** [comment]
I'd also like to get to pulling in the CHANGELOG.md programmatically, but trying to avoid making this a PR of all things.

**Review by sturobson — APPROVED** [review]
looking great! I'm not sure if you're finished with this PR - but approving anyhow

**Comment by khawkins98** [comment]
Nice. Going to revisit and tidy what I've done yesterday, will probably merge sometime today and we can then pick back up and continue "the things".

And also to look at the:

```
  {% set context = header_Crosslink %}
  {% include blocks.section_header %}
```

as discussed in slack

**Comment by khawkins98** [comment]
Have done some additional refinement and merging this one in. Will probably open a new PR today or tomorrow with the nunjucks extends and some other improvements.

Also, we'll need to "touch" many of the Readme files to standardise formatting, which is a bit overdue anyways. 

I think we can do a trick to avoid shipping npm release just because we've updated the readmes ...

**Pull request merged**
