### PR TITLE
enhancement: drop cssnano for native minification

### PR DESCRIPTION
**Pull request by khawkins98**
I noticed some odd output during the cssnano step:

```
[16:40:28] Starting 'vf-css:production'...
--vf-cluster-margin [
  {
    index: 40,
    token: '-',
    type: 9,
    eval: [Function: sub],
    precedence: 1,
    show: '-'
  },
...
```

Looking further I realised gulp-cssnano was a major version behind on cssnano, and investigating further I realised that dart sass now has native minification: https://github.com/sass/dart-sass/issues/221

So this PR:

- drops cssnano
- uses dart sass native minification
- resolves the junk output in the build process
- uses latest dart-sass version

### CODE REVIEW

**Comment by sturobson** [comment]
Sass has always had a `compressed` option, so I’m wondering why I’ve used something like CSSNano etc to do things. 

I guess autoprefixer runs after Sass, so that inclusion doesn’t get minified? 

What’s the output like?

**Comment by khawkins98** [comment]
> Sass has always had a compressed option, so I’m wondering why I’ve used something like CSSNano etc to do things.

when I was looking at "the things" it seemed that while there has been a "compact" option for a long time, it wasn't until 2018 that "compressed" became consistently supported. Then add that we were using the gulp-sass wrapper, that may be why cssnano was the only real choice. 

There are still oddities, like how the JavaScript API only:

> Only the "expanded" and "compressed" values of outputStyle are supported.

https://github.com/sass/dart-sass#javascript-api

---

> I guess autoprefixer runs after Sass, so that inclusion doesn’t get minified?

The prefixed seems smart enough to not inject white space:

```css
/*!
 * Component: @visual-framework/vf-hero
 * Version: 2.0.5
 * Location: components/undefined
 */.vf-hero{--vf-hero--spacing: 2rem;background-color:var(--vf-hero--bg-color, #18974c);background-image:url("https://acxngcvroo.cloudimg.io/v7/https://www.embl.org/files/wp-content/uploads/roundels.png");background-image:var(--vf-hero--bg-image, url("https://acxngcvroo.cloudimg.io/v7/https://www.embl.org/files/wp-content/uploads/roundels.png"));margin-bottom:2rem;margin-bottom:var(--vf-hero--spacing, 2rem);padding:2rem 0;padding:var(--vf-hero--spacing, 2rem) 0}.vf-hero.vf-u-fullbleed::before{background-size:cover;background-size:var(--vf-hero--bg-image-size, cover);z-index:1}.vf-hero__content{background-color:#fff;background-color:var(--vf-hero-content--bg-color, #ffffff);color:#000;color:var(--vf-hero-content--fg-color, #000000);box-shadow:2px 0 3px rgba(0,0,0,.1),-2px 0 3px rgba(0,0,0,.1),0 2px 3px rgba(0,0,0,.1);max-width:60ch;padding:1rem;padding:calc( var(--vf-hero--spacing) / 2);position:relative;width:fit-content;width:-moz-fit-content;z-index:1984}
```


---

> What’s the output like?

As for output, a quick review says it's the same:

New:

```css
/*! Component: @visual-framework/vf-componenet-rollup
 * Version: 1.2.3
 * Location: components/undefined
 * VF Core version in use: 2.2.14
 * Build time: Wed, 23 Dec 2020 07:36:29 GMT
 */:root{--vf-color--green: #18974c;--vf-color--green--darkest: #0a5032;--vf-color--green--dark: #007b53;--vf-color--green--light: #6cc24a;--vf-color--green--lightest: #d0debb;--vf-color--grey: #707372;--vf-color--grey--darkest: #373a36;--vf-color--grey--dark: #54585a;--vf-color--grey--light: #a8a99e;--vf-color--grey--lightest: #d0d0ce;--vf-color--red: #d41645;--vf-color--red--dark: #a6093d;--vf-color--red--light: #e58f9e;--vf-color--blue: #3b6fb6;--vf-color--blue--dark: #193f90;--vf-color--blue--light: #8bb8e8;--vf-color--purple: #734595;--vf-color--purple--dark: #563d82;--vf-color--purple--light: #cba3d8;--vf-color--orange: #f49e17;--vf-color--orange--dark: #b65417;--vf-color--orange--light: #efc06e;--vf-color--yellow: #f4c61f;--vf-color--yellow--dark: #ffb81c;--vf-color--yellow--light: #fdd757;--vf-color--bright-green: #a1be1f;--vf-color--bright-green--dark: #7fb428;--vf-color--bright-green--light: #e2e868}:root{--vf-theme--primary: #3b6fb6;--vf-theme--primary--dark: #193f90;--vf-theme--secondary: #18974c;--vf-theme--secondary--dark: #007b53;--vf-theme--tertiary: #54585a;--vf-theme--quaternary: #f4c61f;--vf-theme--quinary: #d0d0ce}:root{--vf-ui-color--black: #000000;--vf-ui-color--grey: #d8d8d8;--vf-ui-color--grey--light: #f3f3f3;--vf-ui-color--yellow: #fffadc;--vf-ui-color--red: #d32f2f;--vf-ui-color--white: #ffffff;--vf-ui-color--off-white: #fafafa}:root{--vf-body-width: 81.25em;--page-grid-gap: 1rem;--embl-grid-module--prime: 16rem;--embl-grid-spacing-normaliser: 0px}@media(min-width: 75em){:root{--page-grid-gap: 2rem}}/*!
```


Current:

```css
/*! Component: @visual-framework/vf-componenet-rollup
 * Version: 1.2.3
 * Location: components/undefined
 * VF Core version in use: 2.2.14
 * Build time: Mon, 21 Dec 2020 10:40:55 GMT
 */:root{--vf-color--green:#18974c;--vf-color--green--darkest:#0a5032;--vf-color--green--dark:#007b53;--vf-color--green--light:#6cc24a;--vf-color--green--lightest:#d0debb;--vf-color--grey:#707372;--vf-color--grey--darkest:#373a36;--vf-color--grey--dark:#54585a;--vf-color--grey--light:#a8a99e;--vf-color--grey--lightest:#d0d0ce;--vf-color--red:#d41645;--vf-color--red--dark:#a6093d;--vf-color--red--light:#e58f9e;--vf-color--blue:#3b6fb6;--vf-color--blue--dark:#193f90;--vf-color--blue--light:#8bb8e8;--vf-color--purple:#734595;--vf-color--purple--dark:#563d82;--vf-color--purple--light:#cba3d8;--vf-color--orange:#f49e17;--vf-color--orange--dark:#b65417;--vf-color--orange--light:#efc06e;--vf-color--yellow:#f4c61f;--vf-color--yellow--dark:#ffb81c;--vf-color--yellow--light:#fdd757;--vf-color--bright-green:#a1be1f;--vf-color--bright-green--dark:#7fb428;--vf-color--bright-green--light:#e2e868;--vf-theme--primary:#3b6fb6;--vf-theme--primary--dark:#193f90;--vf-theme--secondary:#18974c;--vf-theme--secondary--dark:#007b53;--vf-theme--tertiary:#54585a;--vf-theme--quaternary:#f4c61f;--vf-theme--quinary:#d0d0ce;--vf-ui-color--black:#000;--vf-ui-color--grey:#d8d8d8;--vf-ui-color--grey--light:#f3f3f3;--vf-ui-color--yellow:#fffadc;--vf-ui-color--red:#d32f2f;--vf-ui-color--white:#fff;--vf-ui-color--off-white:#fafafa;--vf-body-width:81.25em;--page-grid-gap:1rem;--embl-grid-module--prime:16rem;--embl-grid-spacing-normaliser:0px}@media (min-width:75em){:root{--page-grid-gap:2rem}}
```

The only difference I've been able to notice is that dart-sass is slightly more aggressive at eating the whitespace. Not preserving a line return before a comment `/*!`, which makes things slightly less scalable. There's probably a way around that later down the line, though.

---

In all:

1. one major downside is that even the local development CSS is compressed, so it's a bit harder to read the CSS. But I suppose the web inspector tooling can de-minify it for you. 
2. I've noticed the non-production build has a source map at the end (`/*# sourceMappingURL=styles.css.map */`) that isn't copied over, so we should either fix it or remove the sourcemap link. But that's not a new issue to this PR>

**Comment by khawkins98** [comment]
> I've noticed the non-production build has a source map at the end (/*# sourceMappingURL=styles.css.map */) that isn't copied over, so we should either fix it or remove the sourcemap link. But that's not a new issue to this PR>

Made a fix for this in 863856e

**Comment by sturobson** [comment]
Other differences:

new -- 1740 bytes
old -- 1665 bytes

new - leaves/generates 'same value' hex as #000000
old - leaves/generates 'same value' hex as #000 

new - leaves space after css custom properties `--vf-color: #F00`
old - removes space after css custom properties `--vf-color:#F00`

Negligble in the grand scheme of things, one less thing to go wrong, and only a slight change here and there.

Happy to remove a dependency and I'm sure the dart Sass implementation will improve some of these things over time.

**Review by sturobson — APPROVED** [review]

**Comment by khawkins98** [comment]
> Happy to remove a dependency and I'm sure the dart Sass implementation will improve some of these things over time.

I didn't really point it out before, but we _have_ to move away from the current setup. cssnano isn't usable inside gulp without a wrapper, and gulp-cssnano has been archived and [not updated in 3 years](https://github.com/ben-eb/gulp-cssnano/issues/103). It was the bug above that tipped me off to this. 

It would be relatively trivial to fork and update the existing gulp-cssnano, but why bother when Sass natively does virtually the same. And that's why we're here :)

**Pull request merged**
