### PR TITLE
✨ the one that adds a new layout component for vertical rhythm / flow

### PR DESCRIPTION
**Pull request by sturobson**

### CODE REVIEW

**Comment by sturobson** [comment]
@khawkins98 this should be good enough to merge in now I reckon.

**Review by khawkins98 — APPROVED** [review]
Looks good. One question: should this be a utility class/component instead? `vf-u-stack`?

**Comment by sturobson** [comment]
> Looks good. One question: should this be a utility class/component instead? `vf-u-stack`?

I think it meets the criteria for layout more. With a utility class being something we could use to override the stacking value if needs be (I'll work that in here now).

There's also [this issue](https://github.com/visual-framework/vf-core/issues/1047) where I think we should look to update `vf-u-fullbleed` to a fully blown layout component.

This also goes back to me thinking … perhaps we should prefix classes with things like `l` for layout `vf-l-stack` `vf-l-grid` etc.

But we're probably too far down the road for that complete rewrite :sob:

**Comment by khawkins98** [comment]
Sounds reasonable enough to me.

**Pull request merged**
