### PR TITLE
📝 the one that updates the label or title of the config files

### LINKED ISSUE #1208: Chore: update component labels
Some component labels (in the `.yml`) are prefixed with "Visual Framework" which is out of place in the overview.

image

### PR DESCRIPTION
**Pull request by sturobson**
This should close #1208

### CODE REVIEW

**Comment by khawkins98** [comment]
I think let's hold on this one until we do the next component release.

**Comment by khawkins98** [comment]
I forgot to merge this in, maybe we can just do it as a norma release

**Review by khawkins98 — APPROVED** [review]

**Comment by sturobson** [comment]
can I merge these in, or shall I leave this with you to merge when you get to sneaking it in?

**Comment by khawkins98** [comment]
Getting ready to do a release, I'll slip these in.

**Pull request merged**
