### PR TITLE
removes all variants

### PR DESCRIPTION
**Pull request by sturobson**

### CODE REVIEW

**Comment by khawkins98** [comment]
all of it in the bin

**Comment by khawkins98** [comment]
Looks good, just one thing: we've lost an example that shows usage of `vf-hero__heading--additional`

**Comment by khawkins98** [comment]
It looks like `vf-hero__heading--additional` is now `vf-hero__heading--kicker`, worth a nunjucks alias so its less of a breaking change, particularly for vf-wp?

```
{% if context.vf_hero_heading_additional %}        
  {% set vf_hero_kicker = context.vf_hero_heading_additional %}
```

**Comment by sturobson** [comment]
> worth a nunjucks alias so its less of a breaking change, particularly for vf-wp?

We can do this -- I was going for a `v3.0.0` release because of the varied breaking changes -- but I guess this addition (heh) will help make a smoother move

**Comment by sturobson** [comment]
@khawkins98 I think this one is ready for another look over now

**Review by khawkins98 — APPROVED** [review]

**Comment by khawkins98** [comment]
Looking good. thank for the tweaks.

**Pull request merged**
