### PR TITLE
Issue-1140 : Refactor console verbose logging for GA events

### PR DESCRIPTION
**Pull request by sandykadam**
Fix for https://github.com/visual-framework/vf-core/issues/1140

### CODE REVIEW

**Comment by khawkins98** [comment]
Thanks for this -- what code formatter settings are you using? We've yet to adopt a standard linting/formatter for the VF JS.

**Comment by sandykadam** [comment]
> Thanks for this -- what code formatter settings are you using? We've yet to adopt a standard linting/formatter for the VF JS.

I used Visual Studio IDE and have set the default "Prettier" formatting when file is saved.

**Comment by khawkins98** [comment]
Thanks. Just want to have a think about code formatting and lining before merging this.

**Comment by sandykadam** [comment]
> Thanks. Just want to have a think about code formatting and lining before merging this.

I have removed the default code formatting

**Review by khawkins98 — APPROVED** [review]

**Comment by khawkins98** [comment]
Looks good, thanks @sandykadam 

I'll just add a changelog entry and merge.

have moved the lining question to a new issue.

**Pull request merged**
