### PR TITLE
Fix/broken import variable

### LINKED ISSUE #1469: Bug: Broken Sass imports, variables
When building the CSS there is missing import and variable. These don't seem to break anything so are mostly annoying.

I can whip up a quick PR for these.

```
    ../../components/vf-banner/index.scss 18:9            root stylesheet

Error: Can't find stylesheet to import.
   ╷
18 │ @import 'vf-navigation--global.scss';
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  ../../components/vf-navigation/index.scss 18:9  root stylesheet
  ../../components/vf-card/index.scss 12:9     root stylesheet

Error: Undefined variable.
   ╷
52 │   color: $vf-link--dark-mode--hover-color;
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  ../../components/vf-sass-config/mixins/_links.scss 52:10        inline-link--dark-mode()
  ../../components/ebi-header-footer/ebi-header-footer.scss 69:5  @import
  ../../components/ebi-header-footer/index.scss 12:9              root stylesheet

```

### PR DESCRIPTION
**Pull request by khawkins98**
Closes #1469

Also does some linting and a formatting fix fro the component library.`

### CODE REVIEW

**Review by sturobson — APPROVED** [review]
single quotes here, double quotes there

**Comment by khawkins98** [comment]
> single quotes here, double quotes there

I do as the linting gods demand.

**Comment by khawkins98** [comment]
Hrm. Our stylelint file does say:

>     "string-quotes": "single",

Will have a quick look before merging.

**Comment by sturobson** [comment]
> I do as the linting gods demand.

Is it the AirBnB linting god that everyone goes in and changes the settings of 😭

**Comment by khawkins98** [comment]
Got it, just needed to throw all the npm devdependencies in the root package.json

**Pull request merged**
