### PR TITLE
Enhancement: use example com

### PR DESCRIPTION
**Pull request by khawkins98**
One for dicussion, but suggest we use the generic example.com domain for links over javascript:void as it makes things a bit more "real".

### CODE REVIEW

**Comment by sturobson** [comment]
the reasoning behind not using a real url is when you click it, you get the visited state. Which might look 'odd' and not help further design and development of vf-core.

**Comment by khawkins98** [comment]
That's what bugs me a bout `js:void` it makes it harder to test visited states.

**Comment by khawkins98** [comment]
At the risk of over engineering, it would be nice if there was a random has on each page load.

**Comment by khawkins98** [comment]
It would "probably" be easy enough to make a vf-core only bit of js that found all the URLs to example.com and appended a `example.com/?randmom=32423432`

**Comment by khawkins98** [comment]
Couldn't resist adding random hashes.

**Comment by khawkins98** [comment]
Had one more thought over the weekend and have revised to work like this:

1. `javascript:void(0);` is the default template-passed URL
2. When JS loads, they're swapped with a hashed URL to example.com

This way we ensure we get non-visited links on page load and then can click links to view visited status.

**Pull request closed without merging**
