### PR TITLE
CHORE - Push some components to v1.0 stable 

### PR DESCRIPTION
**Pull request by khawkins98**
Following on with #680 (CHORE: Refresh component versions), we want to start treating some components as "stable" and should make them v1.0 releases. 

This will help us better handle regressions/breaking changes (requiring full version bumps) and better handle improvements and features by doing "real" semantic versioning.

There are a number that should be eldigble; including:

- vf-content
- vf-link
- vf-grid
- etc.

Anything that goes to v1.0 stable should also satisfy the guide https://visual-framework.github.io/vf-welcome/developing/components/what-is-a-component/

### CODE REVIEW

**Comment by khawkins98** [comment]
There are still many that won't be bumped to stable:

- activity list
- discussion 
- figure
- form
- header
- hero
- masthead 
- news-container
- pagination
- search
- tree
- video

Though when we have time (hah!) we should consider what's up with them/how can we address why they can't go stable yet.

**Comment by sturobson** [comment]
I think we need to nail down some sort of 'official' PR process to get us (me) up-together with things that need to be released. One of those is to make sure changes are added to the `changed.md` file.

**Comment by khawkins98** [comment]
👍 Maybe that's: 

1. Updating the auto-comment bot to have "Did you update the changelog"
2. Not ignoring auto-comment bot (#guilty)

**Comment by khawkins98** [comment]
Though, it's probably only more important now that we're going stable. When they we're pre-/alpha, it was all wild anyways.

**Pull request merged**
