### PR TITLE
Compoennt/vf google analytics improvements

### LINKED ISSUE #1059: VF Google Analytics - misc enhancements
## The problem
Current vf-analytics-google component code has some limitations:

- limited in scope, targeting anchors tags-related events only
- it sometimes ignores the areas where the event is captured
- It is predicated on a  "Click" event; buttons ignore clicks and favourite the "mousedown" instead
- Downloads events are triggered by an event on "a" tags

## The purpose
Purpose of improvements are to:
- [ ]  extend scope to more than "a" tags
- [ ]  detect areas where the event is fired
- [ ]  capture events that ignore "Click" events

Further enhancement might cover in the future:
- [ ]  track Downloads that are triggered by a different mechanism than clicking on  "a" tags
- [ ]  Track more Downloads file types than the ones currently listed

## Proposed solution

The code below replaces the function "vfGaLinkTrackingInit" and aims to resolve to:
- extend scope to more than "a" tags
- detect areas where the event is fired
- capture events that ignore "Click" events

_Notes:_

- the function "getClosestGa" detects the closest HTML element with a "data-vf-google-anlaytics-region" attribute.
- This proposed solution has not been fully tested yet.

```
/**
 * Track page links as events
 * Updated from VF canonical to capture broader set of events
 */
function vfGaLinkTrackingInit() {
  // jQuery("body.google-analytics-loaded .track-with-analytics-events a").on('mousedown', function(e) {
  //   analyticsTrackInteraction(e.target,'Manually tracked area');
  // });
  document.body.addEventListener("mousedown", function (evt) {
    let closestContainer = getClosestGa(evt.target, '[data-vf-google-anlaytics-region]');
    if(closestContainer) {
      let closestGaArea = closestContainer.getAttribute('data-vf-google-anlaytics-region');
      //note evt.target can be a nested element, not the body element, resulting in misfires
      // console.log('clicked from getClosestGa: ', closestGaArea);
      analyticsTrackInteraction(evt.target);
    }
    else {
      var from = findParent('a',evt.target || evt.srcElement);
      if (from){
       /* it's a link, actions here */
      //  console.log('clicked from findParent: ',from);
       analyticsTrackInteraction(from);
      }
    }
  }, false );
  //find first parent with tagName [tagname]
  function findParent(tagname,el){
    while (el){
      if ((el.nodeName || el.tagName).toLowerCase()===tagname.toLowerCase()){
        return el;
      }
      el = el.parentNode;
    }
    return null;
  }
}
/*
* Find closest element that has GA attribute
* @returns {el} the closest element with GA attribute
*/
function getClosestGa (elem, selector) {
  // Element.matches() polyfill
	if (!Element.prototype.matches) {
	    Element.prototype.matches =
	        Element.prototype.matchesSelector ||
	        Element.prototype.mozMatchesSelector ||
	        Element.prototype.msMatchesSelector ||
	        Element.prototype.oMatchesSelector ||
	        Element.prototype.webkitMatchesSelector ||
	        function(s) {
	            var matches = (this.document || this.ownerDocument).querySelectorAll(s),
	                i = matches.length;
	            while (--i >= 0 && matches.item(i) !== this) {}
	            return i > -1;
	        };
	}
	// Get the closest matching element
	for ( ; elem && elem !== document; elem = elem.parentNode ) {
		if ( elem.matches( selector ) ) return elem;
	}
	return null;
};
```

### PR DESCRIPTION
**Pull request by khawkins98**
Closes https://github.com/visual-framework/vf-core/issues/1059

- [x] extend scope to more than "a" tags
- [x] better detect areas where the event is fired
- [x] capture events that ignore "Click" events
- [x] captures more file types (txt,fasta)

### CODE REVIEW

**Comment by khawkins98** [comment]
@ebiwd-jros I've mainly brought over your suggested code in #1059 (thanks for that). 

Does that code do everything you want, or are there more features you would want?

note: I still need to test the changes in this PR

**Comment by khawkins98** [comment]
Note: https://github.com/visual-framework/vf-core/pull/1066/commits/905bec527d433fec897c4881972421bc53f38f9e

fixes typo `data-vf-google-analytics-region` from `data-vf-google-anlaytics-region`

🚨 this may be breaking for some users of alpha.1

**Comment by khawkins98** [comment]
Have done some testing on my local and this seems to work well.

**Comment by ebiwd-jros** [comment]
> @ebiwd-jros I've mainly brought over your suggested code in #1059 (thanks for that).
> 
> Does that code do everything you want, or are there more features you would want?
> 
> note: I still need to test the changes in this PR

Thanks @khawkins98 that's great!

To answer your question, it does the job. As  I mentioned in the issue, i myself haven't had the opportunity to fully test it, and I might come back with additional enhancements in the future.

**Comment by khawkins98** [comment]
Ok, great. Let's go with this and further test and enhance as needed.

**Comment by khawkins98** [comment]
Some related planned work in #968

**Review by sturobson — APPROVED** [review]

**Comment by khawkins98** [comment]
This is now available on npm https://www.npmjs.com/package/@visual-framework/vf-analytics-google

**Pull request merged**
