### PR TITLE
Component/vf summary  event

### PR DESCRIPTION
**Pull request by sturobson**
adds start of summary event component and a rough, wip, don't publish to npm vf-container

### CODE REVIEW

**Comment by khawkins98** [comment]
We'll also need something close to the `vf-summary-jobs` but without the button, this came up in today's standup, I captured the spirit of @markboulton 's  remarks at https://gitlab.ebi.ac.uk/emblorg/backlog/issues/294#note_74327

Basically, idea is for the MVP we'd keep something simpler and text based and we can use the one you've started here when things mature a bit.

But I have no suggestions on how to reconcile the naming of this card-like events "showbox"  and the more listy version. 

Aside: might be confusing to have a `vf-container` component when we have other `vf-*-container` named components.

**Comment by sturobson** [comment]
The `.vf-container` idea probably needs more explanation in an issue. I can remove from this PR

**Comment by sturobson** [comment]
As the 'card-like' `vf-summary--events` has a level of design fanciness removing it would result in something similar to see attached. 

Note: the `vf-summary__title` is smaller in the card compared to the inline `vf-summary--jobs` variant. What I've done in the image is reset it to what the generic `vf-summary__title` sizing is.

Screenshot 2020-02-26 at 16 06 42

**Comment by sturobson** [comment]
updated to include a generic 'list' version when no theme or design applied

**Comment by khawkins98** [comment]
Would also need a description/extra-info -- for some events this could be a traditional text description but for others it might be a list of speaker names, some examples of what that might be:

- "UniProt provides the scientific community with a comprehensive, high-quality and freely accessible resource of protein sequence and functional information. This webinar will guide you through searching, exploring and analysing..."  https://www.ebi.ac.uk/training/online/course/guide-uniprot-students
- "This Masters development programme is aimed at current Research Infrastructures managers and leaders who wish to develop the competencies required to meet the needs of Research Infrastructures in the planning, construction and operation phases." https://www.ebi.ac.uk/training/events/2018/executive-masters-management-research-infrastructures
- "Jill Banfield University of California, BerkeleyDistinguished" https://www.ebi.ac.uk/about/events/seminars
- "Lukas Paul, Jean-Baptiste Mariaux, Lexogen GmbH, Vienna, Austria
Host: Vladimir Benes"  https://www.embl.de/research/seminars/index.php


For stress testing the component, also worth noting that the titles can often be quite long; more examples:

- "Annotate your proteins with the UniProt Functional Annotation system UniFire"
- "EMBL Course: Data Visualisation for Biology: A Practical Workshop on Design, Techniques and Tools"
- "Discovery of a sensory system in the vertebrate spinal cord: roles in development, postural control and innate immunity"

Typically the ones with long titles also have shorter descriptions (list of speakers), but not always.

**Comment by sturobson** [comment]
Screenshot 2020-02-27 at 10 17 56


perhaps there's a need for some content strategy :sob: 

I can fix the height in grid, but … crikey. 

"EMBL Course: Data Visualisation for Biology: A Practical Workshop on Design, Techniques and Tools"

could be "Data Visualisation for Biology: A Practical Workshop" and still make sense.

**Comment by khawkins98** [comment]
Yeah, maybe for the "normal" they just get truncated after XX characters and that becomes the incentive.

**Comment by sturobson** [comment]
This also highlights a 'feature' of CSS grid in how it distributes space available when using the 'auto' things.

notice how the last item is narrower, and also how the layout of each card is different (because there is no subgrid) 
Screenshot 2020-02-27 at 10 24 40

**Comment by sturobson** [comment]
Screenshot 2020-02-27 at 10 28 36


This is probably the best we could get for the 'card-like' version (`vf-summary--easy`).

**Comment by sturobson** [comment]
Screenshot 2020-02-27 at 10 48 06


Here's the default one with the description. 

Is the idea that the 'card like' one with have the description also?

**Comment by sturobson** [comment]
@khawkins98 if we can get this merged in - I can then bring it into my branch that refactors `vf-summary` so it's more nunjucks-y

**Review by khawkins98 — APPROVED** [review]
Some sprinklings of px values (16px, 114px) not sure if the design tokens have corresponding values. Otherwise looks good.

**Comment by sturobson** [comment]
> "Some sprinklings of px values…"

I'll pick this up in the other PR 👍

**Pull request merged**
