### PR TITLE
GA - Add ancestor retrieval for elements nested in label

### PR DESCRIPTION
**Pull request by oss6**
This references #1198

A fix has also been included (`detail` -> `details`).

### CODE REVIEW

**Comment by khawkins98** [comment]
Nice thanks for this.

**Review by khawkins98 — APPROVED** [review]

**Comment by sandykadam** [comment]
@khawkins98 Can you please update npm release?

**Comment by khawkins98** [comment]
Yeah, should have it out in a little bit, trying to get a couple more things into the release.

**Comment by khawkins98** [comment]
This should now be on npm (it's tagged rc.8 as I overlooked something in the PR)

**Comment by oss6** [comment]
Thank you very much Ken

**Comment by khawkins98** [comment]
Sure thing, thanks for the contribution!

**Pull request merged**
