### PR TITLE
Document interoperability of pattern versions

### PR DESCRIPTION
**Pull request by khawkins98**
Relates to #28

### CODE REVIEW

**Comment by khawkins98** [comment]
@sturobson now that we're ready to npm (🍾), following up on previous convos about pattern minor/major version compatibility. I think this is where we landed?

**Comment by sturobson** [comment]
I think we're both seeing versioning points differently

`v1.2.3` … the 1 being the major release, the 2 being the minor release and the 3 being the patch release.

therefore, I think:- 

anything that's 2.x.x should work with each other as we shouldn't be introducing breaking changes 
here.

there's chance to do pre-release commits with Lerna too - so perhaps we can start including those (in the future) as 'this is new, it shouldn't break anything, but it's here if you want to check'

Also - we should look at getting the Visual Regression testing set up so it's more automated - I'll look.at this. This way we can see if changing something in `vf-button` has broken the `vf-job-description--snippet` pattern that uses it.

**Comment by sturobson** [comment]
I'll merge this in now to get things underway to lead to more discussion over versioning and how other patterns would/could use newer/older patterns

**Comment by khawkins98** [comment]
Funny. Was just about to comment. 

I think what you say here is fine -- generally the overall architecture should remain the same for all `v2.x`s.... just like how we've now gone from `v1.x` to `v2.0` for `vf-core`. And while minor versions might not be plug-and-play compatible, they should fundamentally be able to work together... just like how a  jQuery 3.2 plugin might require jQuery core 3.1+.

So revised language:

```
### Versioning of patterns

Pattern versions follow the major releases for compatibility. That is:

- All patterns for `v2.0` should be architecturally compatible with each other;
- Some patterns might require specific minor versions, a `vf-pattern:2.2.x` might require `vf-core:>2.1.x`; and
- Minor versions of packages should generally be inter-compatible to use `vf-pattern-a:2.0.12` with `vf-pattern-b:2.0.2`
```

**Pull request merged**
