### PR TITLE
Enhancement: create reusable tooling for react

### PR DESCRIPTION
**Pull request by khawkins98**
For #1271, I've come up with a way that we can use components in React like so:

`<VfLogo title="test" VfLogoPath={VfLogoPath} />`

We do this by:

- reusing our precompiled NJK templates
- loading nunjucks-slim in react
- writting a small amount of wrapper code, extract:

```js
export const VfLogo = React.memo(({ title, VfLogoPath }: VfLogoProps) => {
  return (
    <div>
        vfNunjucks.render('vf-logo', { logo_href: '/vf-react', image: VfLogoPath, logo_text: title })
    </div>
  )
});
```

### CODE REVIEW

**Review by sturobson — APPROVED** [review]
Will using `render` here create a pain point when things change like we had with recent `vf-hero` updates in static-html-pages?

It only will be a problem if it's `render vf-component--variant` rather than `render vf-component` with the variants added 'inside' the render.

Or have I got the implementation all wrong here?

**Comment by khawkins98** [comment]
So far I've only tried with very simple components and no variants, I'll have a look at how variant would be handled.

**Comment by khawkins98** [comment]
> Will using render here create a pain point when things change like we had with recent vf-hero updates in static-html-pages?

As an aside (and deep dive on Nunjucks templating, as I understand it) you can't "include" a template in this context. The precompiled templates are "self-isolated" and can only be created and rendered.  https://mozilla.github.io/nunjucks/api.html#template

`include` is a way of extending an existing "render environment".

So that's why include works better in 11ty: it extends the existing render function instead of creating a new isolated "render environment"

With react there is, of course, no pre-existing "global nunjucks render environment".

Again, I might be wrong here, but this how I've come to understand the architecture.

**Comment by sturobson** [comment]
Cool. 

From working on updating the `vf-hero` and `vf-card` in static-html-pages I think the way forward is to:

- never `render` the variant specifically but add the variant key/value pair 'inside'

So rather than (in nunjucks):

```
{% render '@vf-card--striped', {
      "component-type": "block",
      "newTheme": "primary",
      "card_href": "https://www.embl.es/",
      "card_title": "Barcelona",
      "card_image": "/assets/emblstatic-homepage/assets/sites/barcelona.jpg",
      "card_text": "EMBL’s site in Spain specialises in tissue biology and disease modelling"
} %}
```

Do

```
{% render '@vf-card', {
      "component-type": "block",
      "newTheme": "primary",
      "variant": "striped",
      "card_href": "https://www.embl.es/",
      "card_title": "Barcelona",
      "card_image": "/assets/emblstatic-homepage/assets/sites/barcelona.jpg",
      "card_text": "EMBL’s site in Spain specialises in tissue biology and disease modelling"
} %}
```

It's still a 'hassle' if there are breaking change updates -- but it would, I think, be easier in the long run.

**Comment by khawkins98** [comment]
Nice would play well with precompiled templates too

**Comment by khawkins98** [comment]
Continuing through this I've hit a complication that we can't import .jsx template from node_modules while using React Create App (https://github.com/facebook/create-react-app/issues/5274#issuecomment-426721106) 

I've worked around this by using native ES6 templates. The syntax is more tedious, but it's much of the same. Update coming.

**Comment by khawkins98** [comment]
Todo for monday:

- [x] revisit docs written
- [x] add a couple more example components (to be considered: tabs, box, button)
- [x] add vf-component.react.js template
- [x] add docs to the component library
- [x] add placeholder "react example" to library

Once published
- [ ] update vf-react

**Comment by khawkins98** [comment]
This should now be ready. I'll plan to review again in the morning.

**Pull request merged**
