### PR TITLE
Load header footer from ContentHub

### PR DESCRIPTION
**Pull request by khawkins98**
A pre-step for in with #158 (PATTERN: embl-content-hub-loader)

### CODE REVIEW

**Comment by khawkins98** [comment]
Now updated with an `embl-content-hub-loader` pattern:
- For #158
- Migrate JS from static pages repo
- Updates to use VF approaches including data-embl-js-content-hub-loader
- Updates templates to no longer load js from static pages repo

**Comment by sturobson** [comment]
I wonder if we need to add `gulp component` generated files that aren't being used?

**Comment by khawkins98** [comment]
Yeah, I don't know. 

- Part of me: delete them, they're junk.
- Other part of me: since it's primarily a CSS framework, better to leave them in as that way you know it wasn't an error .. "this page was intentionally left blank"

If you look at my non-css patterns (boilerplates) you see that I seem to change my mind often.

Feelings?

**Comment by sturobson** [comment]
yep - "since it's primarily a CSS framework, better to leave them in as that way you know it wasn't an error .. "this page was intentionally left blank" - let's go with that.

**Comment by khawkins98** [comment]
Added a new PR for the documentation about empty files: #164

**Pull request merged**
