### PR TITLE
Fix: update and optimise vf core install

### PR DESCRIPTION
**Pull request by khawkins98**
This greatly de-complexifies the VF npm development process.

- no longer need to install the root level
- `yarn install` the thing you need (i.e. tools/vf-core)
- updates the related docs
- also deploys the `develop` branch to on develop

When testing this branch be sure to do a `git clean -fxd`

### CODE REVIEW

**Comment by khawkins98** [comment]
@sturobson  This should also make the `(node:97882) UnhandledPromiseRejectionWarning: Error: Fractal themes must inherit from the base Theme class.` message go away for good.

**Comment by khawkins98** [comment]
Looks like the netlify deploy process would need to be updated after this.

**Review by sturobson — APPROVED** [review]

**Comment by sturobson** [comment]
@khawkins98 can confirm this works

**Comment by sturobson** [comment]
good job

**Comment by sturobson** [comment]
@khawkins98 actually -- maybe not -- getting 'errors' on lots of component pages _and_ all the grid variants have disappeared.

ran git clean -fxd in both the root and tools/vf-core

**Comment by khawkins98** [comment]
It looks like there have been deeper changes to the theming layer in Fractal. I'll see how much of a rebuild it might be for vf-frctl-theme. 

Probably a separate issue.

**Pull request merged**
