### PR TITLE
some updates to the component library pages

### PR DESCRIPTION
**Pull request by sturobson**
- updates the `--global` navigation to match latest
- -[x] updates the `vf-search` to used to match the `vf-search` updates

### CODE REVIEW

**Comment by sturobson** [comment]
@khawkins98 for some reason the homepage search works 'as expected' but `/search/` is blowing up.

There's some additional JS stuff going on I think - which I wasn't expecting :-/ 

Any ideas? 

**edit:** I've narrowed this down to something in the `section.njk`

**Comment by khawkins98** [comment]
Looks like markdown is having its way

**Comment by sturobson** [comment]
@khawkins98 🙏🏼 thank you -- works a charm now.

**Comment by sturobson** [comment]
ugh, /components/ is doing this too :-/ 

I've `git reset --hard origin/this-branch-name` too

**Comment by sturobson** [comment]
this is making things look odd in several places -- I'll try and fix as much as I can.

**Comment by sturobson** [comment]
I _think_ I've fixed any outstanding markdown not working issues

**Comment by khawkins98** [comment]
Looks like the ones that weren't behaving as expected were using the section.njk template and I didn't add `templateEngineOverride: njk, md`.

But have had a click around many pages and looking correct by me.

**Review by khawkins98 — APPROVED** [review]

**Pull request merged**
