### PR TITLE
the one where we update our use of plex mono

### PR DESCRIPTION
**Pull request by sturobson**
This PR is related to #467. So far we have:

- [x] renamed the usage of plex in the design tokens and `vf-code-example` from `5` to `1`.
- [x] make it a Sass variable rather than a map
- [x] reduced the amount of font files needed.

### CODE REVIEW

**Comment by sturobson** [comment]
regarding: 

> make it a Sass variable rather than a map

Because a font being used in a component comes with `font-size`, `font-weight`, and `line-height`it is probably better to keep it as a Sass map of one thing.

Other wise we would need to refactor the `@mixin` that we're using for typography to cope when there's no map and only variables. I don't think we've really go a use case here that necessitates such a larger refactor.

**Comment by sturobson** [comment]
@khawkins98 as you worked on `vf-font-plex-mono` can you look into removing the typefaces we don't need? 

We only need the `regular`/`400` files now

**Comment by khawkins98** [comment]
Have removed the unneeded mono assests, but ...

The Sass size mapping isn't working as expected due to a bug in [`components/vf-sass-config/mixins/_typography.scss`](https://github.com/visual-framework/vf-core/blob/develop/components/vf-sass-config/mixins/_typography.scss): 

https://github.com/visual-framework/vf-core/blob/b09afd050e393c56cbeeadb86da77602a7e44101/components/vf-sass-config/mixins/_typography.scss#L2-L9

☝️ The font map is hardcoded to `$vf-font--sans-serif`, which means `set-type(text-body--1,$vf-font-family--monospace, $custom-margin-bottom: 0);` results in huge text as it references the sans font map:

image

I didn't spot an easy/clean way to fix this...

**Comment by sturobson** [comment]
I'll take a look at this, to fix - then we should be able to add it into `beta2`

**Comment by sturobson** [comment]
This _should_ be good now.

**Comment by khawkins98** [comment]
Meanwhile inside the sass innards

Aside: can't believe I even manage to find a linotype gif.

**Pull request merged**
