### PR TITLE
Enhancement/gulp dart sass

### PR DESCRIPTION
**Pull request by khawkins98**
Subs `gulp-sass` for `gulp-dart-sass` which avoids an unnecessary installation of libsass. 

`gulp-dart-sass` is a fork of `gulp-sass` that removes the libsass dependency, which gulp-sass has said they won't do. 

https://github.com/mattdsteele/gulp-dart-sass#readme

Still investigating "is it worth it"

### CODE REVIEW

**Comment by khawkins98** [comment]
With gulp-dart-sass

```
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 22.41s.
mac-stratcom12:vf-core khawkins$ gulp vf-dev
[15:21:20] Using gulpfile ~/Documents/GitHub/vf-core/gulpfile.js
[15:21:20] Starting 'vf-dev'...
[15:21:20] Starting 'vf-clean'...
[15:21:20] Finished 'vf-clean' after 172 ms
[15:21:20] Starting 'vf-css'...
[15:21:20] Starting 'vf-css:package-info'...
[15:21:21] Finished 'vf-css:package-info' after 400 ms
[15:21:21] Starting 'vf-css:build'...
Notice: Couldn't find ../vf-somepattern/vf-i-dont-exist.scss referenced in /Users/khawkins/Documents/GitHub/vf-core/components/vf-componenet-rollup/index.scss, the CSS won't be included in the build. If this is expect, you might want to comment out the dependency.
Notice: Couldn't find ../vf-local-overrides/vf-local-overrides.scss referenced in /Users/khawkins/Documents/GitHub/vf-core/components/vf-componenet-rollup/index.scss, the CSS won't be included in the build. If this is expect, you might want to comment out the dependency.
[15:21:23] Finished 'vf-css:build' after 2.87 s
[15:21:23] Finished 'vf-css' after 3.27 s
[15:21:23] Starting 'vf-scripts'...
[15:21:23] Starting 'vf-scripts:es5'...
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
[15:21:25] Finished 'vf-scripts:es5' after 1.73 s
[15:21:25] Starting 'vf-scripts:modern'...
[15:21:25] Finished 'vf-scripts:modern' after 3.61 ms
[15:21:25] Finished 'vf-scripts' after 1.73 s
[15:21:25] Starting 'vf-component-assets'...
[15:21:25] Starting 'vf-component-assets:directory'...
[15:21:25] Starting 'vf-component-assets:compiled-css'...
[15:21:25] Starting 'vf-component-assets:js'...
[15:21:26] Finished 'vf-component-assets:compiled-css' after 728 ms
[15:21:26] Finished 'vf-component-assets:js' after 944 ms
[15:21:26] Finished 'vf-component-assets:directory' after 1 s
[15:21:26] Finished 'vf-component-assets' after 1 s
[15:21:26] Starting 'vf-fractal:start'...
✔ Your Visual Framework component library is available at http://localhost:3000
[15:21:29] Finished 'vf-fractal:start' after 2.89 s
[15:21:29] Starting 'vf-lint:scss-soft-fail'...
```

with gulp-sass

```
[4/4] 🔨  Building fresh packages...
✨  Done in 23.83s.
mac-stratcom12:vf-core khawkins$ gulp vf-dev
[15:23:25] Using gulpfile ~/Documents/GitHub/vf-core/gulpfile.js
[15:23:25] Starting 'vf-dev'...
[15:23:25] Starting 'vf-clean'...
[15:23:25] Finished 'vf-clean' after 371 ms
[15:23:25] Starting 'vf-css'...
[15:23:25] Starting 'vf-css:package-info'...
[15:23:26] Finished 'vf-css:package-info' after 456 ms
[15:23:26] Starting 'vf-css:build'...
Notice: Couldn't find ../vf-somepattern/vf-i-dont-exist.scss referenced in /Users/khawkins/Documents/GitHub/vf-core/components/vf-componenet-rollup/index.scss, the CSS won't be included in the build. If this is expect, you might want to comment out the dependency.
Notice: Couldn't find ../vf-local-overrides/vf-local-overrides.scss referenced in /Users/khawkins/Documents/GitHub/vf-core/components/vf-componenet-rollup/index.scss, the CSS won't be included in the build. If this is expect, you might want to comment out the dependency.
[15:23:29] Finished 'vf-css:build' after 2.82 s
[15:23:29] Finished 'vf-css' after 3.27 s
[15:23:29] Starting 'vf-scripts'...
[15:23:29] Starting 'vf-scripts:es5'...
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
[15:23:30] Finished 'vf-scripts:es5' after 1.46 s
[15:23:30] Starting 'vf-scripts:modern'...
[15:23:30] Finished 'vf-scripts:modern' after 3.57 ms
[15:23:30] Finished 'vf-scripts' after 1.47 s
[15:23:30] Starting 'vf-component-assets'...
[15:23:30] Starting 'vf-component-assets:directory'...
[15:23:30] Starting 'vf-component-assets:compiled-css'...
[15:23:30] Starting 'vf-component-assets:js'...
[15:23:31] Finished 'vf-component-assets:compiled-css' after 813 ms
[15:23:31] Finished 'vf-component-assets:js' after 1 s
[15:23:31] Finished 'vf-component-assets:directory' after 1.04 s
[15:23:31] Finished 'vf-component-assets' after 1.04 s
[15:23:31] Starting 'vf-fractal:start'...
✔ Your Visual Framework component library is available at http://localhost:3000
[15:23:35] Finished 'vf-fractal:start' after 3.28 s
[15:23:35] Starting 'vf-lint:scss-soft-fail'...
```

**Comment by khawkins98** [comment]
No difference in `http://localhost:3000/css/styles.css`

Which would be expected.

**Comment by khawkins98** [comment]
I'm not seeing a major advantage of this approach for technical performance, but we can revisit later if we notice "issues"

**Comment by sturobson** [comment]
> we can revisit later if we notice "issues" 

one issue being `@import` in how it works with Sass being deprecated. So we might need to revisit sooner - hence the original PR rather than later.

another being Dart Sass is likely to get fixes faster than LibSass > NodeSass

and another being Dart Sass allows for new CSS features - whereas LibSass > NodeSass does not. [most of these work in Dart Sass, or they're working on it](https://css-tricks.com/when-sass-and-new-css-features-collide/) where as it breaks in LibSass where they're not working on it.

**Comment by sturobson** [comment]
we can ignore my comment here 😭

**Pull request closed without merging**
