### PR TITLE
Initial grafting of 11ty into a component+docs setup

### PR DESCRIPTION
**Pull request by khawkins98**
Part of the [mini documentation sprint](https://docs.google.com/document/d/1VoiZcskLHa7nOMILfS949VzgHAzhkgCObZi31HE51jI/edit), this will allow 11ty to do the navigation+high level docs and allow Fractal to continue making the component docs.

Steps

- [x] Graft 11ty  into `tools/vf-component-library`
- [x] Integrate the fractal environment into 11ty
- [x] Port vf-welcome to `tools/vf-component-library`
- [x] Add a redout of components available
- [x] Documenation of how to use `vf-component-library` 
- [x] All the navigation/presentation stuff to do in 11ty/vf-component-library
- [x] Remap so that `vf-component-library` deploys to gh-page
- [x] Add a search

### CODE REVIEW

**Comment by khawkins98** [comment]
@sturobson I've got enough here that it's worth taking a few minutes tomorrow to catchup on

**Comment by khawkins98** [comment]
@todo for me: investigate loading a local file's contents, a la https://github.com/mozilla/nunjucks/issues/788#issuecomment-332183033

**Comment by sturobson** [comment]
>  I've got enough here that it's worth taking a few minutes tomorrow to catchup on

All I've got so far is a few sheets of paper trying to work out the IA 😭

**Comment by khawkins98** [comment]
Have made a few tweaks on the layout, still work to be done but some is dependent on other things. 

I think we're quite close here. @sturobson let's have a chat tomorrow and see if we can ship it and enhance.

**Comment by khawkins98** [comment]
@sturobson have improved search/component finding. 

Also hid the njk template from utility components.

More to be done in the mid term, but I don't have anything else on my to-do list for this PR.

**Review by sturobson — APPROVED** [review]

**Comment by sturobson** [comment]
@khawkins98 I'll let you push the big green button here. 👏👏👏👏👏

**Pull request merged**
