### PR TITLE
chore: vf-card conditional title and alt example

### PR DESCRIPTION
**Pull request by khawkins98**
- adds alt text to examples
- conditional display of `card_title`

### CODE REVIEW

**Comment by sturobson** [comment]
Have you got the latest from `develop` because at the top of the `vf-card.mjk` I get:

```
{%- if context %}
  {% set card_href = context.card_href %}

  {% set card_title = context.card_title %}
  {% set card_subtitle = context.card_subtitle %}
  {% set card_text = context.card_text %}
  {% set card_image = context.card_image %}
  {% set card_image__alt = context.card_image__alt %}

  {% set theme = context.theme %}
  {% set variant = context.variant %}

  {% set id = context.id %}
  {% set modifiers = context.modifiers %}
  {% set override_class = context.override_class %}
{% endif %}
```

Which looks different to what you're editing here.

**Comment by khawkins98** [comment]
Think that's the same, what's different? https://github.com/visual-framework/vf-core/blob/6958d05cbe3541acc35c3d0a83fbee9d8e8020cf/components/vf-card/vf-card.njk

**Comment by sturobson** [comment]
looks like there's less here -- https://github.com/visual-framework/vf-core/pull/1079/files#diff-5d4072670831661cea61311fba63cfd5 -- is that 'because github'?

**Comment by khawkins98** [comment]
Ah, gitlab has just collpased the "same" bits. 
image

I added white space trim to some tags

**Comment by sturobson** [comment]
I'll take this branch and add somethings that got picked up (theming) so we can get it all in one merge - if that's cool?

**Comment by khawkins98** [comment]
👍

**Comment by sturobson** [comment]
can you explain more in what this means?

> conditional display of card_title

I read it as if there's no title, don't show anything - but the code changes the `h3` to a `span`‽

**Comment by khawkins98** [comment]
At first, I had the whole thing commented out but then realised the href needs to be wrapped in `.vf-card__title` to do its thing.

This is the best way I thought of to change the fewest things while not putting out an empty h3.

**Comment by sturobson** [comment]
How does a screenreader react if there's no title to the link? I'm assuming it will read out the url.

**Comment by sturobson** [comment]
I actually don't have anything to change by the looks of it - the issue I saw with link underlines on wwwdev must be inheriting it from some other CSS somewhere - so will investigate there instead.

**Review by sturobson — APPROVED** [review]

**Comment by khawkins98** [comment]
> I actually don't have anything to change by the looks of it - the issue I saw with link underlines on wwwdev must be inheriting it from some other CSS somewhere - so will investigate there instead.

Yeah that was because the markup was so old. the whole vf-card was an `a` element

**Comment by sturobson** [comment]
> Yeah that was because the markup was so old. the whole vf-card was an a element

Ah, yes. That'll explain it - I'm guessing that the updates to `static-html-pages` will fix this too.

**Pull request merged**
